<?php

$products = array(
  0 => array(
    "id" => 1,
    "title" => "Nintendo Switch",
    "description" => "herkhfaw",
    "price" => 3200,
    "image" => "https://picsum.photos/200/300?random=1",
    "category" => "electronics",
  ),
  1 => array(
    "id" => 2,
    "title" => "Apple Watch",
    "description" => "herkhfaw",
    "price" => 2990,
    "image" => "https://picsum.photos/200/300?random=2",
    "category" => "electronics",
  ),
  2 => array(
    "id" => 3,
    "title" => "Sony Bluetooth Headset",
    "description" => "herkhfaw",
    "price" => 2500,
    "image" => "https://picsum.photos/200/300?random=3",
    "category" => "electronics",
  ),
  3 => array(
    "id" => 4,
    "title" => "MacBook Pro 15\"",
    "description" => "herkhfaw",
    "price" => 30000,
    "image" => "https://picsum.photos/200/300?random=4",
    "category" => "electronics",
  ),
  4 => array(
    "id" => 5,
    "title" => "",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=5",
    "category" => "electronics",
  ),
  5 => array(
    "id" => 6,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=6",
    "category" => "men",
  ),
  6 => array(
    "id" => 7,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=7",
    "category" => "men",
  ),
  7 => array(
    "id" => 8,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=8",
    "category" => "men",
  ),
  8 => array(
    "id" => 9,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=9",
    "category" => "men",
  ),
  9 => array(
    "id" => 10,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=10",
    "category" => "men",
  ),
  10 => array(
    "id" => 11,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=11",
    "category" => "jewelery",
  ),
  11 => array(
    "id" => 12,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=12",
    "category" => "jewelery",
  ),
  12 => array(
    "id" => 13,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=13",
    "category" => "jewelery",
  ),
  13 => array(
    "id" => 14,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=14",
    "category" => "jewelery",
  ),
  14 => array(
    "id" => 15,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=15",
    "category" => "jewelery",
  ),
  15 => array(
    "id" => 16,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=16",
    "category" => "women",
  ),
  16 => array(
    "id" => 17,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=17",
    "category" => "women",
  ),
  17 => array(
    "id" => 18,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=18",
    "category" => "women",
  ),
  18 => array(
    "id" => 19,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=19",
    "category" => "women",
  ),
  19 => array(
    "id" => 20,
    "title" => "hello",
    "description" => "herkhfaw",
    "price" => 168,
    "image" => "https://picsum.photos/200/300?random=20",
    "category" => "women",
  ),
);
