<?php

$products = array(
  0 => array(
    "id" => 1,
    "title" => "Nintendo Switch",
    "description" => "Nintendo Switch is designed to fit your life, transforming from home console to portable system in a snap.",
    "price" => 3200,
    "image" => "https://picsum.photos/200/300?random=1",
    "category" => "electronics",
  ),
  1 => array(
    "id" => 2,
    "title" => "Apple Watch",
    "description" => "Measure your blood oxygen level with a revolutionary sensor and app. Take an ECG anytime, anywhere. See your fitness metrics at a glance with the enhanced Always-On Retina display. With Apple Watch Series 6 on your wrist, a healthier, more active, more connected life is within reach.",
    "price" => 3990,
    "image" => "https://picsum.photos/200/300?random=2",
    "category" => "electronics",
  ),
  2 => array(
    "id" => 3,
    "title" => "Sony Bluetooth Headset",
    "description" => "To maximise noise-cancelling performance, the WH-1000XM4 headphones incorporate two technologies: Personal Noise-Cancelling Optimiser, designed specifically for you, and Atmospheric-Pressure Optimising, designed specifically for air travel.",
    "price" => 2500,
    "image" => "https://picsum.photos/200/300?random=3",
    "category" => "electronics",
  ),
  3 => array(
    "id" => 4,
    "title" => "MacBook Pro 15\"",
    "description" => "With AMD graphics, an innovative Trackpad, nine hours of battery life and one of the fastest hard drives we've ever tested, the 2015 MacBook Pro is a force to be reckoned with.",
    "price" => 30000,
    "image" => "https://picsum.photos/200/300?random=4",
    "category" => "electronics",
  ),
  4 => array(
    "id" => 5,
    "title" => "Fujifilm Instax Square SQ1",
    "description" => "Prints square size images to capture more of the moment – 1.5x the size of a mini print! Rounded and textured grip for a comfortable hold (includes separate thumb grip attachment). Auto-exposure for bright images. Selfie mirror and one-touch selfie mode. 2 - CR2 Battery",
    "price" => 1390,
    "image" => "https://picsum.photos/200/300?random=5",
    "category" => "electronics",
  ),
  5 => array(
    "id" => 6,
    "title" => "Derby shoes",
    "description" => "Derby shoes with open lacing at the front. Canvas linings and insoles. Heel 2.5 cm.",
    "price" => 1500,
    "image" => "https://picsum.photos/200/300?random=6",
    "category" => "men",
  ),
  6 => array(
    "id" => 7,
    "title" => "Espadrilles",
    "description" => "Espadrilles woven in a cotton blend with a braided jute trim around the soles, elastic gores in the sides and a loop at the back. Fabric linings and insoles, and patterned soles. Height of soles 1.6 cm.",
    "price" => 649,
    "image" => "https://picsum.photos/200/300?random=7",
    "category" => "men",
  ),
  7 => array(
    "id" => 8,
    "title" => "Sports joggers",
    "description" => "Sports joggers in jersey made from a cotton blend with taped details. Elasticated waist, a slightly lower crotch with a ventilating mesh section, and zipped side pockets for safe storage of small items.",
    "price" => 349,
    "image" => "https://picsum.photos/200/300?random=8",
    "category" => "men",
  ),
  8 => array(
    "id" => 9,
    "title" => "Roll-top backpack",
    "description" => "Backpack in water-repellent nylon with a handle at the top, adjustable shoulder straps and a roll-top opening with a tab and carabiner hook. One zipped outer compartment. Lined in woven fabric made from recycled polyester. Depth 12 cm. Width 30 cm. Total height 63 cm.",
    "price" => 399,
    "image" => "https://picsum.photos/200/300?random=9",
    "category" => "men",
  ),
  9 => array(
    "id" => 10,
    "title" => "Track jacket Regular Fit",
    "description" => "Track jacket in heavy jersey with a zip down the front and a mesh-lined hood with an elastic drawstring and plastic cord stopper. Chest pocket with a concealed zip, discreet side pockets, ribbing at the cuffs, and narrow elastication at the back of the hem. Slightly longer and rounded at the back.",
    "price" => 499,
    "image" => "https://picsum.photos/200/300?random=10",
    "category" => "men",
  ),
  10 => array(
    "id" => 11,
    "title" => "Chunky ring",
    "description" => "Chunky 18k gold ring for all occasions. Available in sizes 7 to 12.",
    "price" => 4000,
    "image" => "https://picsum.photos/200/300?random=11",
    "category" => "jewelry",
  ),
  11 => array(
    "id" => 12,
    "title" => "Beaded bracelet",
    "description" => "Elastic bracelet with irregular plastic beads and a spherical plastic bead with a metal finish.",
    "price" => 99,
    "image" => "https://picsum.photos/200/300?random=12",
    "category" => "jewelry",
  ),
  12 => array(
    "id" => 13,
    "title" => "Hoop earrings",
    "description" => "Earrings in metal. Four pairs of hoop earrings in various sizes.",
    "price" => 169,
    "image" => "https://picsum.photos/200/300?random=13",
    "category" => "jewelry",
  ),
  13 => array(
    "id" => 14,
    "title" => "Pendant Necklace",
    "description" => "Thin metal chain necklace with an antiqued finish and plastic stone pendant. Adjustable length with a trigger clasp and a small pendant engraved with the designer’s logo at one end. The zinc content of the necklace is recycled.",
    "price" => 129,
    "image" => "https://picsum.photos/200/300?random=14",
    "category" => "jewelry",
  ),
  14 => array(
    "id" => 15,
    "title" => "Two-strand necklace",
    "description" => "Two-strand necklace of chunky chains in different designs. Adjustable length and a trigger clasp.",
    "price" => 199,
    "image" => "https://picsum.photos/200/300?random=15",
    "category" => "jewelry",
  ),
  15 => array(
    "id" => 16,
    "title" => "Oversized denim shirt",
    "description" => "Oversized shirt in sturdy cotton denim with a collar, metal buttons down the front and a yoke at the back. Flap chest pockets with a button, dropped shoulders, long sleeves with buttoned cuffs, and a rounded hem.",
    "price" => 299,
    "image" => "https://picsum.photos/200/300?random=16",
    "category" => "women",
  ),
  16 => array(
    "id" => 17,
    "title" => "Linen-blend jumpsuit",
    "description" => "Jumpsuit in an airy viscose and linen weave with a deep V-neck and buttons down the front. Short sleeves with turn-ups, a detachable tie belt at the waist and wide, ankle-length legs with patch pockets at the sides.",
    "price" => 349,
    "image" => "https://picsum.photos/200/300?random=17",
    "category" => "women",
  ),
  17 => array(
    "id" => 18,
    "title" => "V-neck linen blouse",
    "description" => "Sleeveless blouse in linen with a deep V-neck front and back, buttons down the front and a seam at the waist with a flared peplum.",
    "price" => 129,
    "image" => "https://picsum.photos/200/300?random=18",
    "category" => "women",
  ),
  18 => array(
    "id" => 19,
    "title" => "Chunky-soled sandals",
    "description" => "Chunky-soled sandals with adjustable fabric straps and hook and loop fastenings. Imitation leather insoles. Height of soles 7 cm.",
    "price" => 199,
    "image" => "https://picsum.photos/200/300?random=19",
    "category" => "women",
  ),
  19 => array(
    "id" => 20,
    "title" => "Padded hooded outdoor jacket",
    "description" => "Outdoor jacket in woven fabric with a double-layered hood, stand up collar and zip down the front with a chin guard. Padded front and back sections, zipped side pockets, long raglan sleeves with thumbholes at the cuffs and inset side panels in sturdy jersey lined with thermal fleece. Longer and rounded at the back. Partly lined.",
    "price" => 349,
    "image" => "https://picsum.photos/200/300?random=20",
    "category" => "women",
  ),
);
